<?php

namespace TestBundle\Repository;

/**
 * ProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName($first)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM TestBundle:Program p ORDER BY p.name ASC'
            )
            ->setFirstResult($first)
            ->setMaxResults(5);
    }
}
