# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
## REPOSITORY
#    myStuff.repository.province:
#        class: AppBundle/Form/Repository/ProvinceRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\Province']
#
#    myStuff.repository.city:
#        class: AppBundle/Form/Repository/CityRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments: ['AppBundle\Entity\City']